sudo: false
language: python
python:
  - "3.6"
env:
  - CYTOKIT_CACHE_DIR=${TRAVIS_BUILD_DIR}/cache
cache:
  directories:
    - cache
install:
  - env
  # Example modified from https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION nose
  - source activate test-environment
  # Upgrade pip to make it possible to disable progress bars
  - pip install -U pip>=10.0.1
  # Install flowdec and cvutils from repo directly until published
  - pip install --progress-bar off -e "git+https://github.com/hammerlab/flowdec.git#egg=flowdec&subdirectory=python"
  - mkdir -p $(python -m site --user-site)
  - echo "$(pwd)/python/applications" >> $(python -m site --user-site)/local.pth
  - cd python/pipeline
  - pip install --progress-bar off .[tf]
  - pip install coveralls pylint
script:
  - nosetests --exe -sv tests/ --with-coverage --cover-inclusive --cover-package=cytokit
  - bash ./.lint.sh
after_success:
  - coveralls